module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Tests', [
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Moscow',
        number: 1,
        distance: 1090,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Vladivostok',
        number: 2,
        distance: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Kirov',
        number: 2,
        distance: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Tver',
        number: 5,
        distance: 700,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Kolomna',
        number: 4,
        distance: 600,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Ekaterinburg',
        number: 5,
        distance: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Saint Petersburg',
        number: 7,
        distance: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Voronezh',
        number: 8,
        distance: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Astrakhan',
        number: 9,
        distance: 1000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Bryansk',
        number: 12,
        distance: 1100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Vologda',
        number: 29,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Vladikavkaz',
        number: 25,
        distance: 2100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Gorno-Altaysk',
        number: 25,
        distance: 1220,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Ivanovo',
        number: 23,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Kazan',
        number: 16,
        distance: 1550,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Izhevsk',
        number: 9,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Irkutsk',
        number: 15,
        distance: 1500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Kaliningrad',
        number: 21,
        distance: 1310,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Lipetsk',
        number: 18,
        distance: 2400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Murom',
        number: 31,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Krasnoyarsk',
        number: 29,
        distance: 3200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Novosibirsk',
        number: 24,
        distance: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Nizhny Novgorod',
        number: 27,
        distance: 2200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Petrozavodsk',
        number: 8,
        distance: 1870,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Perm',
        number: 21,
        distance: 4990,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Tyumen',
        number: 30,
        distance: 2480,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Tests', null, {});
  },
};
